### ISSUE TITLE
Release 3.1?

### ISSUE THREAD

**Issue by efenderbosch** [spotbugs/spotbugs-maven-plugin#13]
Spotbugs 3.1 has been released, but this plugin is still in RC status. Any timeline on publishing to maven?

**Comment by hazendaz** [comment]
It's published under rc8.  It's only not final as its waiting on user feedback of a feature for gui.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
see [here](http://search.maven.org/#artifactdetails%7Ccom.github.spotbugs%7Cspotbugs-maven-plugin%7C3.1.0-RC8%7Cmaven-plugin) for the currently released version which is against spotbugs 3.1.0.  While we are making every attempt to stay on version alignment we needed at least one more RC so a bug against original plugin could be verified fixed.  We have since had one additoinal bug potentially against original plugin that is fixed only here.  I don't anticipate any more RC on this but rather 3.1.0 release as soon as that feedback comes in.  I'll leave this open as a place holder.  Thanks.

**Comment by hazendaz** [comment]
@efenderbosch 3.1.0 has been released and 3.1.1 is coming right behind it.  This is fully supported on java 9 too now.
