### ISSUE TITLE
Not support baseline maven 3.3.3 for building

### ISSUE THREAD

**Issue by liuhu** [spotbugs/spotbugs-maven-plugin#272]
Not support baseline maven 3.3.3 for building
![image](https://user-images.githubusercontent.com/1286384/98218774-2400a480-1f87-11eb-9abf-7cf749a626fd.png)

My jenkins maven version is：
![image](https://user-images.githubusercontent.com/1286384/98218335-9c1a9a80-1f86-11eb-94c5-6a21147f6c17.png)

**Comment by hazendaz** [comment]
@liuhu Its possible your path isn't exactly correct.  Maven is what decides that check and its stating 3.2.5 so 3.2.5 or better would be allowed.  I don't have such an old copy of maven and would not really advice using such old maven version (jdk same thing).  If you can, upgrade but further review your environment variables as there is potentially a mix of what is being used.  You can run maven with more output and show the snippet of what it used during the full build cycle.  Older maven is certainly allowed though as we are explicitely allowing really old maven still due to some other user needs, otherwise we would force 3.6.3 at this point in time.

Per maven plugin standards, the setting in question is this.

```
  <prerequisites>
    <maven>3.2.5</maven>
  </prerequisites>
```

And that does match the error which tells me it thinks you are using something older.

**Comment by hazendaz** [comment]
closing issue as no response and setup issue as plugin only requires 3.2.5 currently.  Future releases will likely require latest regardless so advisable to use latest maven 3.6.3 and ensure it is properly setup on path.
