### ISSUE TITLE
[BUG] Dependency upon build-tools not used in reporting plugin

### ISSUE THREAD

**Issue by rhbvkleef** [spotbugs/spotbugs-maven-plugin#313]
We have a multi-module project:

```
skrol
|-- pom.xml
|-- build-tools
|   |-- src
|   |   `-- main
|   |       `-- resources
|   |           `-- build-tools
|   |               `-- findbugs
|   |                   `-- excludes.xml
|   `-- pom.xml
|-- skrol-client
|-- skrol-core
`-- skrol-service
```

and we have a reporting plugin defined:

```xml
<project>
    <reporting>
        <plugin>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-maven-plugin</artifactId>
            <configuration>
                <excludeFilterFile>build-tools/findbugs/excludes.xml</excludeFilterFile>
            </configuration>
        </plugin>
    </reporting>
</project>
```

and we defined a build plugin:

```xml
<project>
    <build>
        <plugins>
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs</artifactId>
                        <version>4.2.2</version>
                    </dependency>
                    <dependency>
                        <groupId>REDACTED</groupId>
                        <artifactId>build-tools</artifactId>
                        <version>1.0</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>4.2.2</version>
            </plugin>
        </pluginManagement>
    </build>
</project>
```

And this does not work. The manual provides an alternative, which is to add the `build-tools` module as an extension in the pom.xml of each of the submodules, but this creates the problem that the build-tools need to be installed before any goal on either the root project or any of the sub-projects can be executed. This isn´t desirable behaviour, and I expect that a setup such as shown above should be possible, as several other plugins can be configured in exactly the same way, and in fact, the findbugs plugin could be configured like this.

**Comment by hazendaz** [comment]
@rhbvkleef Have you tried moving the dependencies to plugin management?  Also can you try simply with 'build-tools' not being nested?  If neither works, this support likely never worked and would need looked at further.  If you could put together a sample project that fails to work, you could start by adding integration test to the current project then looking at 'ResourceHelper.groovy' to understand where its going wrong.  Any PR resulting from this I can get released out right away.  All the current examples (outside of javadoc stating otherwise) only work against a file in the current project scope.

**Comment by rhbvkleef** [comment]
> Have you tried moving the dependencies to plugin management? Also can you try simply with 'build-tools' not being nested?

Unfortunately, neither works. I'll look at setting up a sample project.

**Comment by hazendaz** [comment]
<excludeFilterFile>build-tools/findbugs/excludes.xml</excludeFilterFile> is incorrect after looking at this again.  It needs the entire path to that as ran from the root.  So that would be <excludeFilterFile>build-tools/src/main/resources/findbugs/excludes.xml</excludeFilterFile>.  Closing as this was configuration issue and not related to the plugin.
