### ISSUE TITLE
github code search does not work on forked repositories

### ISSUE THREAD

**Issue by walkerbrianpatrick** [spotbugs/spotbugs-maven-plugin#391]
If you attempt to search the source code on the github web interface, it replies 'forked repositories cannot be searched'. As the previous home for the plugin is archived, consider making this the root project, and forking from the appropriate commit to gleclaire/findbugs-maven-plugin.

**Comment by hazendaz** [comment]
What specifically are you using that does not work?  It works fine searching from this page, here is an example query (https://github.com/?q=spotbugs-maven-plugin).  If you are using other methods, see https://docs.github.com/en/search-github/searching-on-github/searching-in-forks.  You could also star the project so it ends up auto indexed if it is above original.

Not sure exactly what method you are using otherwise or if behaviour is simply different since I'm the maintainer but all the other suggestions are completely manual and not likely going to occur.

**Comment by walkerbrianpatrick** [comment]
I read the article you linked, it looks like they don't index forks until it is more popular than the root repo. Dropping a star is the least I can do, but won't solve the problem until loads more people do it. 

Strange that you can do code search as maintainer...

**Comment by hazendaz** [comment]
Guess I should have also starred the project, its tied with the root now.  Just needs one more bump then this should be resolved.

**Comment by hazendaz** [comment]
@walkerbrianpatrick Think this is now resolved, can you confirm it works for you now?

**Comment by hazendaz** [comment]
closing as resolved.
