### ISSUE TITLE
Validation doesn't fail for project with test sources only

### ISSUE THREAD

**Issue by MetroMarv** [spotbugs/spotbugs-maven-plugin#454]
# Steps to reproduce

- create a new Maven repository with only sources in `src/test/..`
  - there should be no java classes in `src/main/`
- create a file that violates any Spotbugs rule in `src/test/`
- add the Spotbugs Maven plugin to the pom.xml file
  - set also the plugin's setting `includeTests` to `true` ([includeTests](https://spotbugs.github.io/spotbugs-maven-plugin/verify-mojo.html#includeTests))
- execute Spotbugs by calling `mvn package` and `mvn spotbugs:check`

# Observed behavior

No violation detected -> Build green

```
[INFO] --- spotbugs-maven-plugin:4.7.1.0:spotbugs (spotbugs) @ one-performance-tests ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
```

# Expected behavior

Violation is printed and build fails.

# Notes

- the when using the option `xmlOutput=true` the XML file is correctly written and contains violations
- in the class `BaseViolationCheckMojo` ([L490](https://github.com/spotbugs/spotbugs-maven-plugin/blob/760dea77281211cb4b985306a79cfc3105934ff8/src/main/groovy/org/codehaus/mojo/spotbugs/BaseViolationCheckMojo.groovy#L490)) only executes the violation verification if there are class files in the projects output directory (usually `target/classes`), which is empty for projects only having test sources
- when we add a class like `src/main/Test.java` to our project, Spotbugs prints the violations and fails the build

**Comment by hazendaz** [comment]
Thank you for the detailed information here.  This sounds like an easy fix.  I will take a look at this as soon as I can.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Marvin Rensing ***@***.***>
Sent: Monday, July 18, 2022 9:45:15 AM
To: spotbugs/spotbugs-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spotbugs/spotbugs-maven-plugin] Validation doesn't fail for project with test sources only (Issue #454)


Steps to reproduce

  *   create a new Maven repository with only sources in src/test/..
     *   there should be no java classes in src/main/
  *   create a file that violates any Spotbugs rule in src/test/
  *   add the Spotbugs Maven plugin to the pom.xml file
     *   set also the plugin's setting includeTests to true (<https://spotbugs.github.io/spotbugs-maven-plugin/verify-mojo.html#includeTests>)
  *   execute Spotbugs by calling mvn package and mvn spotbugs:check

Observed behavior

No violation detected -> Build green

[INFO] --- spotbugs-maven-plugin:4.7.1.0:spotbugs (spotbugs) @ one-performance-tests ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....


Expected behavior

Violation is printed and build fails.

Notes

  *   the when using the option xmlOutput=true the XML file is correctly written and contains violations
  *   in the class BaseViolationCheckMojo (L490<https://github.com/spotbugs/spotbugs-maven-plugin/blob/760dea77281211cb4b985306a79cfc3105934ff8/src/main/groovy/org/codehaus/mojo/spotbugs/BaseViolationCheckMojo.groovy#L490>) only executes the violation verification if there are class files in the projects output directory (usually target/classes), which is empty for projects only having test sources
  *   when we add a class like src/main/Test.java to our project, Spotbugs prints the violations and fails the build
