### ISSUE TITLE
Break with findbugs

### ISSUE THREAD

**Issue by elharo** [spotbugs/spotbugs-maven-plugin#930]
This branch is [2091 commits ahead of](https://github.com/spotbugs/spotbugs-maven-plugin/compare/gleclaire%3Afindbugs-maven-plugin%3Amaster...master) gleclaire/findbugs-maven-plugin:master.

I think it's safe to say at this point, this plugin will never be merged back. My git fu is mediocre at best, but is there anyway we could break the link so that the spotbugs plugin is independent?

**Comment by hazendaz** [comment]
That has been asked a few times, will look into it.  Yes it will never be merged back. @gleclaire is part of this repo too but left around time we did the rebranding effort.  For a while it was problematic for folks to find issues in code due to not enough stars but we eventually over came that.  Its a pain for me from time to time now depending how I do releases if I need to raise a PR off main repo as it tries to go upstream.  So I'll look to getting it broke from the original.

**Comment by hazendaz** [comment]
For reference, don't want to do it now as its a bit of a pain.  But here is link on how to do it using bare repo and mirror.  Not a hard process just not one I look forward too with listed negative issues I have to reset up.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork

**Comment by hazendaz** [comment]
Raised a help desk ticket to github on this to get a detached repository that didn't lose any history.  The self service would lose the history.  Not sure why that isn't just available as it didn't take long.  Anyway, this no longer points to a parent project.  Closing as completed.
